name: Deploy to EC2 

on:
  push:
    branches:
      - main   

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: | 
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ${{ secrets.SERVER }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      env:
        HOST: ${{ secrets.SERVER }}
        USER: ubuntu 
      run: |
        cd ${{ github.workspace }}
        scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -r gradient.html assets ${USER}@${HOST}:/var/www/html
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${USER}@${HOST} '
          sudo rm /var/www/html/index.html
          sudo mv /var/www/html/gradient.html /var/www/html/index.html
          sudo systemctl restart apache2
        '